const val SERVER_KEY_ALGORITHM = "RSA"
const val SERVER_KEY_SIZE = 4096

const val SERVER_CERTIFICATE_ALGORITHM = "SHA256withRSA"

const val KEY_EXCHANGE_ALGORITHM = "DH"
const val KEY_EXCHANGE_KEY_SIZE = 4096

const val MESSAGE_ENCRYPTION_ALGORITHM = "AES"
const val MESSAGE_ENCRYPTION_KEY_TRANSFORMATION = "AES/CBC/PKCS5Padding"

const val USER_PASSWD_HASH_ALG = "SHA-256"
